### PR TITLE
Adding dynamic layers 

### PR DESCRIPTION
**Pull request by lyashevska**
Related to https://github.com/point-cloud-radar/bird-cloud-gnn/issues/137

### CODE REVIEW

**Comment by bart1** [comment]
Maybe instead of trying to merge this is is not easier to start from an uptodate branch and merge this line : `model = GCN(len(dataset.features), [(16, nn.ReLU()), (16, nn.ReLU()), (2, None)])`

**Comment by lyashevska** [comment]
Yes, I see there are many changes. I either rebase it or create a new pull request.

**Comment by bart1** [comment]
Due to delays I could add some flexiblity to also make elu and leakyrelu options for the main package

**Comment by lyashevska** [comment]
Conflicts has been resolved.

**Pull request merged**
